### ISSUE TITLE
示例文件无法运行

### ISSUE THREAD

**Issue by qtbgo** [ctpbee/ctpbee#152]
您好！感谢您的代码。
我pip install ctpbee后，运行示例代码easy_use.py,出现如下错误，请怎样才能运行起来？
Traceback (most recent call last):
  File "e:/myquant/ctpbee-master/examples/easy_use.py", line 30, in <module>
    market.start(log_output=True)
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\app.py", line 300, in start
    self._running(logout=log_output)
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\app.py", line 244, in _running
    self.init_interface()
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\app.py", line 263, in init_interface
    MdApi, TdApi = Interface.get_interface(self)
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\interface\__init__.py", line 46, in get_interface
    return cls.load_interface(app.config.get("INTERFACE"))
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\interface\__init__.py", line 39, in load_interface
    from ctpbee.interface.ctp_mini import MMdApi, MTdApi
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\interface\ctp_mini\__init__.py", line 1, in <module>
    from .md_api import MMdApi
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\interface\ctp_mini\md_api.py", line 4, in <module>
    from .lib import *
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee\interface\ctp_mini\lib.py", line 2, in <module>
    from ctpbee_api.ctp_mini import *
  File "e:\myquant\venv_quant389\lib\site-packages\ctpbee_api\ctp_mini\__init__.py", line 1, in <module>
    from .CMdApi import MdApi as MiniMdApi
ModuleNotFoundError: No module named 'ctpbee_api.ctp_mini.CMdApi'

**Comment by somewheve** [comment]
暂时别用mini接口

**Comment by qtbgo** [comment]
那现在有没有可以运行的示例？

**Comment by somewheve** [comment]
你要用mini接口 ？  我现在发布了一个新的版本 应该是可以了 你可以试试  注意先卸载ctpbee_api

**Comment by qtbgo** [comment]
我无所谓用哪个接口，我就想能有一个可运行的示例。不知道有木有？

**Comment by somewheve** [comment]
直接把名字改成 配置里面的 ctp_mini换成ctp就可以跑了

**Comment by qtbgo** [comment]
吧哪个文件里的ctp_min名字改成ctp？easy_use.py里并没有名字ctp_min

**Comment by qtbgo** [comment]
测试了，python3.8下不行，python3.7下可以

**Comment by somewheve** [comment]
我在等人的issue  回复 到时候分发三个版本的  不好意思

qtbgo ***@***.***> 于2021年8月28日周六 下午2:53写道：

**Comment by somewheve** [comment]
我已经分发了 windows和linux的 cp36 cp37 cp38 cp39 的 包了  pip uninstall ctpbee_api  然后再pip install ctpbee_api就可以了

**Comment by qtbgo** [comment]
太好了，谢谢哈

**Comment by somewheve** [comment]
ctpbee 也可以更新下 1.4.6

**Comment by qtbgo** [comment]
朋友，有没有联系方式或群啥的？股票接口做好了吗？

**Comment by somewheve** [comment]
没啥联系方式      没做股票 短期不考虑 我太忙l

**Comment by somewheve** [comment]
开发没啥动力

Huang Wang ***@***.***> 于2021年9月7日周二 下午5:06写道：

>  没啥联系方式      没做股票 短期不考虑 我太忙l
>
